2021-11-24 22:39:29,680 INFO    MainThread:43993 [wandb_setup.py:_flush():71] setting env: {}
2021-11-24 22:39:29,680 INFO    MainThread:43993 [wandb_setup.py:_flush():71] setting login settings: {'anonymous': 'must'}
2021-11-24 22:39:29,681 INFO    MainThread:43993 [wandb_init.py:_log_setup():371] Logging user logs to /home/snamburi/Debarshi/wandb/run-20211124_223929-l35m6zit/logs/debug.log
2021-11-24 22:39:29,681 INFO    MainThread:43993 [wandb_init.py:_log_setup():372] Logging internal logs to /home/snamburi/Debarshi/wandb/run-20211124_223929-l35m6zit/logs/debug-internal.log
2021-11-24 22:39:29,681 INFO    MainThread:43993 [wandb_init.py:init():404] calling init triggers
2021-11-24 22:39:29,681 INFO    MainThread:43993 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2021-11-24 22:39:29,681 INFO    MainThread:43993 [wandb_init.py:init():449] starting backend
2021-11-24 22:39:29,681 INFO    MainThread:43993 [backend.py:_multiprocessing_setup():95] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-11-24 22:39:29,719 INFO    MainThread:43993 [backend.py:ensure_launched():199] starting backend process...
2021-11-24 22:39:29,742 INFO    MainThread:43993 [backend.py:ensure_launched():204] started backend process with pid: 44007
2021-11-24 22:39:29,744 INFO    MainThread:43993 [wandb_init.py:init():458] backend started and connected
2021-11-24 22:39:29,745 INFO    MainThread:43993 [wandb_init.py:init():519] updated telemetry
2021-11-24 22:39:29,747 INFO    MainThread:43993 [wandb_init.py:init():549] communicating current version
2021-11-24 22:39:30,556 INFO    MainThread:43993 [wandb_init.py:init():554] got version response 
2021-11-24 22:39:30,556 INFO    MainThread:43993 [wandb_init.py:init():564] communicating run to backend with 30 second timeout
2021-11-24 22:39:30,753 INFO    MainThread:43993 [wandb_init.py:init():592] starting run threads in backend
2021-11-24 22:39:32,231 INFO    MainThread:43993 [wandb_run.py:_console_start():1816] atexit reg
2021-11-24 22:39:32,232 INFO    MainThread:43993 [wandb_run.py:_redirect():1690] redirect: SettingsConsole.REDIRECT
2021-11-24 22:39:32,232 INFO    MainThread:43993 [wandb_run.py:_redirect():1695] Redirecting console.
2021-11-24 22:39:32,236 INFO    MainThread:43993 [wandb_run.py:_redirect():1751] Redirects installed.
2021-11-24 22:39:32,236 INFO    MainThread:43993 [wandb_init.py:init():619] run started, returning control to user process
2021-11-24 22:39:32,236 INFO    MainThread:43993 [wandb_run.py:_config_callback():962] config_cb None None {'epochs': 5, 'batch_size': 1, 'learning_rate': 1e-05, 'val_percent': 0.1, 'save_checkpoint': True, 'img_scale': 0.5, 'amp': False}
2021-11-24 22:39:33,197 INFO    MainThread:43993 [wandb_run.py:_atexit_cleanup():1786] got exitcode: 1
2021-11-24 22:39:33,198 INFO    MainThread:43993 [wandb_run.py:_restore():1758] restore
2021-11-24 22:39:35,283 INFO    MainThread:43993 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 543
  total_bytes: 543
}

2021-11-24 22:39:35,390 INFO    MainThread:43993 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 543
  total_bytes: 543
}

2021-11-24 22:39:35,504 INFO    MainThread:43993 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 543
  total_bytes: 543
}

2021-11-24 22:39:35,793 INFO    MainThread:43993 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 543
  total_bytes: 16900
}

2021-11-24 22:39:35,900 INFO    MainThread:43993 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 543
  total_bytes: 16900
}

2021-11-24 22:39:36,002 INFO    MainThread:43993 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 16900
  total_bytes: 16900
}

2021-11-24 22:39:36,105 INFO    MainThread:43993 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 16900
  total_bytes: 16900
}

2021-11-24 22:39:36,208 INFO    MainThread:43993 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 16900
  total_bytes: 16900
}

2021-11-24 22:39:36,310 INFO    MainThread:43993 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 16900
  total_bytes: 16900
}

2021-11-24 22:39:36,507 INFO    MainThread:43993 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 16900
  total_bytes: 16900
}

2021-11-24 22:39:36,766 INFO    MainThread:43993 [wandb_run.py:_wait_for_finish():1916] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 16900
  total_bytes: 16900
}
local_info {
}

2021-11-24 22:39:37,944 INFO    MainThread:43993 [wandb_run.py:_append_files():2184] logging synced files
